apiVersion: v1
kind: Pod
metadata:
  name: test-pod-create3
  labels:
    kubernetes.io/os: mac-dummy 
    version: v0.0.1
spec:
  containers:
  - image: test-image
    name: test-name
    command: [
          "test-cmd"
        ]
    args: [
      "test-arg"
    ]
    env:
    - name: KILL_DELAY
      value: "300"
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
  nodeSelector:
    kubernetes.io/role: worker
